name: stc-todo

services:
  server:
    container_name: stc-todo-api
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/stc-todo
    env_file:
      - server/.env
    ports:
      - 3000:3000
    depends_on:
      mongodb:
        condition: service_healthy
        restart: true
  mongodb:
    image: mongo
    container_name: stc-todo-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./server/data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/stc-todo --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  client:
    container_name: stc-todo-frontend
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/sites-enabled/default.conf
      - ./nginx/log/:/var/log/nginx:rw
      - ./certbot/www/:/var/www/certbot/:ro # Certbot challenge folder
      - ./certbot/conf/:/etc/letsencrypt/:ro # Certbot output folder
    depends_on:
      - server
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw # Certbot challenge folder
      - ./certbot/conf/:/etc/letsencrypt/:rw # Certbot output folder
    depends_on:
      - client
