name: stc-todo

services:
  server:
    container_name: stc-todo-api
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/stc-todo
    env_file:
      - server/.env
    ports:
      - 3000:3000
    depends_on:
      mongodb:
        condition: service_healthy
        restart: true
  mongodb:
    image: mongo
    container_name: stc-todo-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./server/data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/stc-todo --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  client:
    container_name: stc-todo-frontend
    build:
      context: client
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:3000
    ports:
      - 80:8080
